//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Анализаторы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Анализаторы()
        {
            this.ОказанныеУслуги = new HashSet<ОказанныеУслуги>();
        }
    
        public int ID_анализатора { get; set; }
        public string Модель { get; set; }
        public string СерийныйНомер { get; set; }
        public System.DateTime ДатаУстановки { get; set; }
        public Nullable<bool> Архивный { get; set; }
        public Nullable<System.DateTime> ДатаАрхивации { get; set; }
        public string ПричинаАрхивации { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОказанныеУслуги> ОказанныеУслуги { get; set; }
    }
}
