//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.ОказанныеУслуги = new HashSet<ОказанныеУслуги>();
        }
    
        public int ID_заказа { get; set; }
        public int ID_пациента { get; set; }
        public System.DateTime ДатаСоздания { get; set; }
        public string СтатусЗаказа { get; set; }
        public Nullable<bool> Архивный { get; set; }
        public Nullable<System.DateTime> ДатаАрхивации { get; set; }
        public string ПричинаАрхивации { get; set; }
    
        public virtual Пациенты Пациенты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОказанныеУслуги> ОказанныеУслуги { get; set; }
    }
}
