//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Лаборанты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Лаборанты()
        {
            this.ОказанныеУслуги = new HashSet<ОказанныеУслуги>();
            this.Услуги = new HashSet<Услуги>();
        }
    
        public int ID_лаборанта { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string ФИО { get; set; }
        public Nullable<System.DateTime> ПоследнийВход { get; set; }
        public Nullable<bool> Архивный { get; set; }
        public Nullable<System.DateTime> ДатаАрхивации { get; set; }
        public string ПричинаАрхивации { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОказанныеУслуги> ОказанныеУслуги { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Услуги> Услуги { get; set; }
    }
}
