//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ОказанныеУслуги
    {
        public int ID_оказанной_услуги { get; set; }
        public int ID_заказа { get; set; }
        public int ID_услуги { get; set; }
        public Nullable<int> ID_лаборанта { get; set; }
        public Nullable<int> ID_анализатора { get; set; }
        public Nullable<System.DateTime> ДатаНачала { get; set; }
        public Nullable<System.DateTime> ДатаЗавершения { get; set; }
        public string СтатусУслуги { get; set; }
        public Nullable<int> ВремяВыполнения { get; set; }
    
        public virtual Анализаторы Анализаторы { get; set; }
        public virtual Заказы Заказы { get; set; }
        public virtual Лаборанты Лаборанты { get; set; }
        public virtual Услуги Услуги { get; set; }
    }
}
