//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пациенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пациенты()
        {
            this.Заказы = new HashSet<Заказы>();
        }
    
        public int ID_пациента { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string ФИО { get; set; }
        public System.DateTime ДатаРождения { get; set; }
        public string СерияПаспорта { get; set; }
        public string НомерПаспорта { get; set; }
        public string Телефон { get; set; }
        public string Email { get; set; }
        public string НомерПолиса { get; set; }
        public string ТипПолиса { get; set; }
        public Nullable<int> ID_компании { get; set; }
        public Nullable<bool> Архивный { get; set; }
        public Nullable<System.DateTime> ДатаАрхивации { get; set; }
        public string ПричинаАрхивации { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заказы> Заказы { get; set; }
        public virtual СтраховыеКомпании СтраховыеКомпании { get; set; }
    }
}
