//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public int ID_Пользователя { get; set; }
        public string Имя { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string IP_Адрес { get; set; }
        public Nullable<System.DateTime> Последний_вход { get; set; }
        public string Услуги { get; set; }
        public int Тип { get; set; }
        public Nullable<int> ID_Роли { get; set; }
        public byte[] Фото { get; set; }
    
        public virtual Роли Роли { get; set; }
    }
}
