//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Услуги
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Услуги()
        {
            this.ОказанныеУслуги = new HashSet<ОказанныеУслуги>();
            this.Лаборанты = new HashSet<Лаборанты>();
        }
    
        public int ID_услуги { get; set; }
        public string КодУслуги { get; set; }
        public string Наименование { get; set; }
        public decimal Стоимость { get; set; }
        public int СрокВыполнения { get; set; }
        public Nullable<decimal> СреднееОтклонение { get; set; }
        public Nullable<bool> Архивный { get; set; }
        public Nullable<System.DateTime> ДатаАрхивации { get; set; }
        public string ПричинаАрхивации { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОказанныеУслуги> ОказанныеУслуги { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Лаборанты> Лаборанты { get; set; }
    }
}
